image: openjdk:8

pipelines:
  default:
    - step:                   # define the build pipeline for the tag
        caches:
          - gradle
        name: Build and Test
        script:
          - ./gradlew clean build
  tags:                         # add the 'tags' section
    v*:                         # specify the tag
      - step:                   # define the build pipeline for the tag
          caches:
            - gradle
          name: Build and Release
          script:
            - ./gradlew clean build bintrayUpload bintrayPublish
